name: Build and Push Docker Image
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 2: Iniciar sesión en Docker Hub o GitHub Container Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }} # Asegúrate de que este secreto esté configurado

      # Si usas GitHub Container Registry, puedes reemplazar la acción anterior por:
      # - name: Log in to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}


     # 3. Construir la imagen de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          use-feature: "buildx"
      - name: Build Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/mangoswebv4:latest . --push

