name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 4. Iniciar sesión en el GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }} # Asegúrate de que este secreto esté configurado

      # 5. Construir la imagen de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          use-feature: "buildx"
      - name: Build Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/mangoswebv4:latest . --push


