name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 2: Iniciar sesión en GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }} # Asegúrate de que este secreto esté configurado

      # Paso 3: Listar los archivos (opcional, para depuración)
      - name: List files
        run: ls -al

      # Paso 4: Construir y subir la imagen Docker
      - name: Build Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/mangoswebv4:latest . --push
